theme: jekyll-theme-cayman
<!DOCTYPE html>
<html>
    <head> 
<meta charset="utf-8">
        <title>端口5个6</title>
    </head>
 
<body>

    <h1>我的第一段 JavaScript</h1>
    <p>请输入数字，如果输入的值不是数字，会弹框</p>
    <input id="demo" type="text">
    <script>
        function myFunction()
    {
        var x=document.getElementById("demo").value;
        if(x==""||isNaN(x))
        {
            alert("不是数字");
        }
    }
    </script>
    
    
    <button type="button" onclick="myFunction()">点一哈</button>
    
</body>
</html>